'use server';

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';
import type { ChangeOrderItem } from '@/types';

/** Supabase PostgREST error code for "JSON object requested, multiple (or no) rows returned" (used with .single()) */
const SUPABASE_NOT_FOUND = 'PGRST116';

async function verifyProjectOwnership(projectId: string, userId: string) {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('projects')
    .select('id')
    .eq('id', projectId)
    .eq('user_id', userId)
    .maybeSingle();
  if (error || !data) throw new Error('Forbidden');
}

async function verifyChangeOrderOwnership(changeOrderId: string, userId: string) {
  const supabase = await createClient();
  const { data: co } = await supabase
    .from('change_orders')
    .select('project_id')
    .eq('id', changeOrderId)
    .maybeSingle();
  if (!co) throw new Error('Forbidden');
  await verifyProjectOwnership(co.project_id, userId);
  return co;
}

export async function createChangeOrder(projectId: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  await verifyProjectOwnership(projectId, user.id);

  const { data: requests } = await supabase
    .from('scope_requests')
    .select('*')
    .eq('project_id', projectId)
    .eq('is_out_of_scope', true)
    .eq('status', 'pending');

  if (!requests || requests.length === 0) {
    throw new Error('没有可生成报价单的超范围需求');
  }

  const { data: project } = await supabase
    .from('projects')
    .select('hourly_rate')
    .eq('id', projectId)
    .single();

  const rate = project?.hourly_rate || 0;

  const items: ChangeOrderItem[] = requests.map(r => ({
    description: r.description,
    estimated_hours: r.estimated_hours || 0,
    rate,
    amount: (r.estimated_hours || 0) * rate,
  }));

  const total_amount = items.reduce((sum, item) => sum + item.amount, 0);

  const { data: changeOrder, error } = await supabase
    .from('change_orders')
    .insert({ project_id: projectId, items, total_amount })
    .select()
    .single();

  if (error) throw error;

  await supabase
    .from('scope_requests')
    .update({ status: 'included_in_quote' })
    .in('id', requests.map(r => r.id));

  revalidatePath(`/projects/${projectId}/change-order`);
  return changeOrder;
}

export async function getChangeOrder(projectId: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  await verifyProjectOwnership(projectId, user.id);

  const { data, error } = await supabase
    .from('change_orders')
    .select('*')
    .eq('project_id', projectId)
    .order('created_at', { ascending: false })
    .limit(1)
    .single();

  if (error && error.code === SUPABASE_NOT_FOUND) return null;
  if (error) throw error;
  return data;
}

export async function sendChangeOrder(id: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  await verifyChangeOrderOwnership(id, user.id);

  // share_token is auto-generated by DB on INSERT; just update status
  const { data, error } = await supabase
    .from('change_orders')
    .update({ status: 'sent' })
    .eq('id', id)
    .select()
    .single();

  if (error) throw error;
  revalidatePath(`/projects/${data.project_id}/change-order`);
  return data;
}

export async function getDeviationStats(projectId: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');

  await verifyProjectOwnership(projectId, user.id);

  const [deliverablesRes, scopeRes] = await Promise.all([
    supabase.from('deliverables').select('status').eq('project_id', projectId),
    supabase
      .from('scope_requests')
      .select('estimated_hours, is_out_of_scope')
      .eq('project_id', projectId),
  ]);

  const deliverables = deliverablesRes.data ?? [];
  const scopeRequests = scopeRes.data ?? [];

  const total_deliverables = deliverables.length;
  const completed_deliverables = deliverables.filter(d => d.status === 'completed').length;
  const progress_percent = total_deliverables > 0
    ? Math.round((completed_deliverables / total_deliverables) * 100)
    : 0;

  const outOfScope = scopeRequests.filter(r => r.is_out_of_scope);
  const out_of_scope_count = outOfScope.length;
  const estimated_extra_hours = outOfScope.reduce((sum, r) => sum + (r.estimated_hours || 0), 0);

  return {
    total_deliverables,
    completed_deliverables,
    progress_percent,
    out_of_scope_count,
    estimated_extra_hours,
  };
}
